
# services:
#   activity-supplier-app:
#     build: ../
#     container_name: activity-supplier-app_container
#     ports:
#       - '5000:5000'
#     volumes:
#       - ./activity-supplier-app:/activity-supplier-app
#       - ./activity-supplier-app/node_modules:/activity-supplier-app/node_modules
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: activity-supplier-app_frontend  
  backend: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"    #external:internal 
    container_name: activity-supplier-app_backend